import { CharType } from '../../char-type/char-type.entity';
import { Classes } from '../../classes/classes.entity';
import { Gender } from '../../gender/gender.entity';
import { Species } from '../../species/species.entity';
import { User } from '../../user/user.entity';

export const characterSeed = [
  {
    name: 'Aragorn',
    type: { id: 1 } as CharType,
    class: { id: 9 } as Classes,
    gender: { id: 2 } as Gender,
    species: { id: 11 } as Species,
    subclass: 'Ranger of the North',
    secondClass: null,
    secondSubclass: null,
    customSpecies: null,
    subSpecies: null,
    customGender: null,
    hair: 'Dark',
    eyes: 'Grey',
    height: '6 ft',
    appearance: 'A tall man with a kingly aura and weathered face.',
    avatar: 'https://example.com/avatars/aragorn.jpg',
    createdBy: { id: 5 } as User,
  },

  {
    name: 'Legolas',
    type: { id: 1 } as CharType,
    class: { id: 9 } as Classes,
    gender: { id: 2 } as Gender,
    species: { id: 4 } as Species,
    subclass: 'Woodland Archer',
    secondClassId: null,
    secondSubclass: null,
    customSpecies: null,
    subSpecies: null,
    customGender: null,
    hair: 'Blonde',
    eyes: 'Blue',
    height: '5.8 ft',
    appearance: 'A graceful elf with long blonde hair and sharp eyesight.',
    avatar: 'https://example.com/avatars/legolas.jpg',
    createdBy: { id: 5 } as User,
  },
  {
    name: 'Gimli',
    type: { id: 1 } as CharType,
    class: { id: 6 } as Classes,
    gender: { id: 2 } as Gender,
    species: { id: 3 } as Species,
    subclass: 'Axe-Wielder',
    secondClassId: null,
    secondSubclass: null,
    customSpecies: null,
    subSpecies: null,
    customGender: null,
    hair: 'Red',
    eyes: 'Brown',
    height: '4.5 ft',
    appearance: 'A stout dwarf with a long braided beard.',
    avatar: 'https://example.com/avatars/gimli.jpg',
    createdBy: { id: 5 } as User,
  },
  {
    name: 'Frodo',
    type: { id: 1 } as CharType,
    class: { id: 13 } as Classes,
    gender: { id: 2 } as Gender,
    species: { id: 10 } as Species,
    subclass: 'Ring-Bearer',
    secondClassId: null,
    secondSubclass: null,
    customSpecies: null,
    subSpecies: null,
    customGender: null,
    hair: 'Brown',
    eyes: 'Green',
    height: '3.5 ft',
    appearance: 'A cheerful hobbit with curly hair and a kind face.',
    avatar: 'https://example.com/avatars/frodo.jpg',
    createdBy: { id: 5 } as User,
  },
  {
    name: 'Gandalf',
    type: { id: 1 } as CharType,
    class: { id: 11 } as Classes,
    gender: { id: 2 } as Gender,
    species: { id: 15 } as Species,
    subclass: 'Wizard of the White Council',
    secondClassId: null,
    secondSubclass: null,
    customSpecies: null,
    subSpecies: null,
    customGender: null,
    hair: 'White',
    eyes: 'Blue',
    height: '5.9 ft',
    appearance: 'An old wizard with a long beard and wise eyes.',
    avatar: 'https://example.com/avatars/gandalf.jpg',
    createdBy: { id: 5 } as User,
  },
  {
    name: 'Boromir',
    type: { id: 1 } as CharType,
    class: { id: 6 } as Classes,
    gender: { id: 2 } as Gender,
    species: { id: 11 } as Species,
    subclass: 'Captain of Gondor',
    secondClassId: null,
    secondSubclass: null,
    customSpecies: null,
    subSpecies: null,
    customGender: null,
    hair: 'Brown',
    eyes: 'Brown',
    height: '6.1 ft',
    appearance: 'A noble man with a strong build and determined face.',
    avatar: 'https://example.com/avatars/boromir.jpg',
    createdBy: { id: 5 } as User,
  },
  {
    name: 'Samwise',
    type: { id: 1 } as CharType,
    class: { id: 13 } as Classes,
    gender: { id: 2 } as Gender,
    species: { id: 10 } as Species,
    subclass: 'Loyal Companion',
    secondClassId: null,
    secondSubclass: null,
    customSpecies: null,
    subSpecies: null,
    customGender: null,
    hair: 'Brown',
    eyes: 'Blue',
    height: '3.6 ft',
    appearance: 'A stout hobbit with a kind face and curly hair.',
    avatar: 'https://example.com/avatars/samwise.jpg',
    createdBy: { id: 5 } as User,
  },
];
